2025-08-28 17:53:36,034 INFO    MainThread:19986 [wandb_setup.py:_flush():80] Current SDK version is 0.21.1
2025-08-28 17:53:36,035 INFO    MainThread:19986 [wandb_setup.py:_flush():80] Configure stats pid to 19986
2025-08-28 17:53:36,035 INFO    MainThread:19986 [wandb_setup.py:_flush():80] Loading settings from /Users/davidebuoso/.config/wandb/settings
2025-08-28 17:53:36,035 INFO    MainThread:19986 [wandb_setup.py:_flush():80] Loading settings from /Users/davidebuoso/Desktop/dev/adv_fail/wandb/settings
2025-08-28 17:53:36,035 INFO    MainThread:19986 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-08-28 17:53:36,035 INFO    MainThread:19986 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /Users/davidebuoso/Desktop/dev/adv_fail/wandb/run-20250828_175336-btun9ax5/logs/debug.log
2025-08-28 17:53:36,035 INFO    MainThread:19986 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /Users/davidebuoso/Desktop/dev/adv_fail/wandb/run-20250828_175336-btun9ax5/logs/debug-internal.log
2025-08-28 17:53:36,040 INFO    MainThread:19986 [wandb_init.py:init():830] calling init triggers
2025-08-28 17:53:36,040 INFO    MainThread:19986 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'exp_name': 'sac', 'seed': 1, 'torch_deterministic': True, 'cuda': True, 'track': True, 'wandb_project_name': 'cleanRL', 'wandb_entity': None, 'capture_video': False, 'env_id': 'Hopper-v4', 'total_timesteps': 1000000, 'num_envs': 32, 'buffer_size': 1000000, 'gamma': 0.99, 'tau': 0.005, 'batch_size': 256, 'learning_starts': 5000.0, 'policy_lr': 0.0003, 'q_lr': 0.001, 'policy_frequency': 2, 'target_network_frequency': 1, 'alpha': 0.2, 'autotune': True, 'eval_on_finish': False, 'eval_episodes': 10, 'eval_deterministic': True, 'use_failure_buffer': False, 'failure_penalty_weight': 0.5, 'mixed_failure_fraction': 0.3, 'max_failure_clusters': 20, 'failure_distance_threshold': 0.5, '_wandb': {'code_path': 'code/sac.py'}}
2025-08-28 17:53:36,040 INFO    MainThread:19986 [wandb_init.py:init():871] starting backend
2025-08-28 17:53:36,268 INFO    MainThread:19986 [wandb_init.py:init():874] sending inform_init request
2025-08-28 17:53:36,299 INFO    MainThread:19986 [wandb_init.py:init():882] backend started and connected
2025-08-28 17:53:36,302 INFO    MainThread:19986 [wandb_init.py:init():953] updated telemetry
2025-08-28 17:53:36,321 INFO    MainThread:19986 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-28 17:53:37,039 INFO    MainThread:19986 [wandb_init.py:init():1029] starting run threads in backend
2025-08-28 17:53:37,184 INFO    MainThread:19986 [wandb_run.py:_console_start():2494] atexit reg
2025-08-28 17:53:37,184 INFO    MainThread:19986 [wandb_run.py:_redirect():2342] redirect: wrap_raw
2025-08-28 17:53:37,184 INFO    MainThread:19986 [wandb_run.py:_redirect():2411] Wrapping output streams.
2025-08-28 17:53:37,184 INFO    MainThread:19986 [wandb_run.py:_redirect():2434] Redirects installed.
2025-08-28 17:53:37,186 INFO    MainThread:19986 [wandb_init.py:init():1075] run started, returning control to user process
2025-08-28 17:53:37,187 INFO    MainThread:19986 [wandb_run.py:_tensorboard_callback():1589] tensorboard callback: runs/Hopper-v4__sac__1__1756396415, True
2025-08-28 17:57:18,266 INFO    MsgRouterThr:19986 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-08-28 17:57:18,784 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,791 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,792 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,792 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,793 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,793 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,794 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,794 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,795 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,795 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,795 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,796 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,796 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,796 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,797 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,797 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,798 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,798 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,799 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,800 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,800 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,800 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,802 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,802 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,803 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,804 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,805 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,805 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,806 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,806 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,806 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,807 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-28 17:57:18,807 ERROR   MainThread:19986 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/davidebuoso/miniforge3/envs/tdp/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
